/*

  < null & undefined basic 1 >

  💬 를 적절한 값으로 고쳐주세요!

*/

let empty;

if (empty === undefined) {
  alert("🎉");
}

/*

  < null & undefined basic 2 >

  💬 를 적절한 값으로 고쳐주세요!

*/


const empty = null;

if (empty === null) {
  alert("🎉");
}

/*

  < null & undefined basic 3 >

  💬 를 적절한 값으로 고쳐주세요!

*/

const empty1 = null;
let empty2;

const result = (empty1 === empty2);

if (result === false) {
  alert("🎉");
}