/*

  < Primitive basic 1 >

  💬 를 적절한 값으로 고쳐주세요!

*/

const person1 = "Jett";
const person2 = "Jett";

const result = (person1 === person2);

if (result === true) {
  alert("🎉");
}


/*

  < Primitive basic 2 >

  💬 를 적절한 값으로 고쳐주세요!

*/

let person1 = "Jett"
const person2 = person1;

person1 = "Justin";

if (person2 === "Jett") {
  alert("🎉");
}


/*

  < Primitive basic 3 >

  💬 를 적절한 값으로 고쳐주세요!

*/

let vaco = "Vanilla";

vaco[2] = "N";
vaco[6] = "A";
console.log(vaco);

if (vaco === "Vanilla") {
  alert("🎉");
} 